name: C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore GitHubTestingAutomation.sln

    - name: Build Solution
      run: msbuild GitHubTestingAutomation.sln /p:Configuration=Debug

    - name: Run Tests
      run: UnitTest-IsPrime\x64\Debug\UnitTest-IsPrime.exe
